// Generated by Wrangler
// After adding bindings to `wrangler.toml`, regenerate this interface via `npm run cf-typegen`
interface CloudflareBindings {
  ASSETS: {
    fetch: (input: Request | string) => Promise<Response>;
  }
}
